name: Update TV Schedules

on:
  workflow_dispatch:
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run generator
   run: |
          cd $GITHUB_WORKSPACE
          python generate.py

      - name: Commit and push
        run: |
          git config user.name "TvSchedule"
          git config user.email "example@example.com"
          git add rss/*.ics
          git commit -m "Update schedules" || echo "No changes"
          git push || true
